### PR TITLE
Add Laravel 9 support

### PR DESCRIPTION
**Pull request by stephenjude**
- Add Laravel 9 support

### CODE REVIEW

**Comment by stephenjude** [comment]
Hi @codebyray

Please review. I will wait for you response

**Comment by stephenjude** [comment]
Hi @codebyray

Please review. I will wait for you response

**Review by ramay2088 — APPROVED** [review]

**Comment by ramay2088** [comment]
anyone to accept this pull request? @codebyray  @stephenjude

**Comment by stephenjude** [comment]
Not sure @ramay2088

**Comment by ramay2088** [comment]
I am waiting for this package only to upgrade my project

**Comment by stephenjude** [comment]
Same here

**Comment by ramay2088** [comment]
is there any way I can use this pull request of you ?

**Comment by stephenjude** [comment]
I will have to fork and release Laravel 9 version of the package.

**Comment by ramay2088** [comment]
can you please do it we will come back to this after it will get updated

**Comment by stephenjude** [comment]
okay

**Comment by stephenjude** [comment]
@ramay2088 I just release the Laravel 9 support

https://github.com/stephenjude/laravel-review-rateable

**Comment by ramay2088** [comment]
Thank you so much buddy

**Comment by codebyray** [comment]
This pull request has been merged. My apologies for the time is has taken, was down sick for the last week.

**Comment by stephenjude** [comment]
@codebyray sorry about that. Hope you are okay now getting better now?

**Comment by codebyray** [comment]
@stephenjude better now for sure, thank you for asking.

**Pull request merged**
